### ISSUE TITLE
New Feature: Expand & Collapse feature with virtual list view control. 

### ISSUE THREAD

**Issue by GV1072** [Redth/Maui.VirtualListView#32]
Dear Team,

I trust this message finds you well. I wanted to bring to your attention some challenges we are facing during the migration of our large enterprise application from Xamarin Forms to MAUI.

Our application relies heavily on a grouping list view, where items are dynamically removed and added to achieve the expand and collapse feature.

As part of the migration to MAUI, we've encountered the following issues with the list view control:

iOS - https://github.com/dotnet/maui/issues/19186
Android - https://github.com/dotnet/maui/issues/19334

We seek your guidance and assistance in resolving these issues. Any suggestions or fixes would be greatly appreciated.

Additionally, considering the significance of the expand and collapse feature, we propose adding this functionality to the virtual list view. We believe this enhancement would benefit many users.

Your support in addressing these concerns is highly valued.

Thank you,
Gopi V

**Comment by Redth** [comment]
Have you tried this? Is there an actual bug you're seeing? repro? more info?

**Comment by Redth** [comment]
I have a branch started, this is not working currently and I'm a bit puzzled as to why.  I do plan to make this work.

**Comment by Redth** [comment]
Ahh i misunderstood, you want the groups to expand/collapse?  That is not a scenario I'm looking to support in this control.  I was thinking this was issue #29 

In any case, closing since it's either not a feature I'm going to support, or it's a duplicate.

If you really wanted to mimic this behaviour you could probably modify your adapter to return a different number of items per section depending on if the section was collapsed or not (return 0 if collapsed or the real number if not).
